apps/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index.as_view(), name="index"),
]

apps/offers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.index.as_view(), name="index"),
]

apps/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.loginView, name="login"),
    path('logout', views.logoutView, name="logout"),
    path('dashboard', views.DashboardAdminView.as_view(), name="dashboard_admin"),
    path('create-candicate', views.CandidateCreateView.as_view(), name="create_candidate"),
    path('list-candidates',views.CandidateListView.as_view(), name="list_candidates"),
    path('detail-candidates/<int:pk>',views.CandidateDetailView.as_view(), name="detail_candidates"),
    

    # path('signup', views.signupView, name="signup"),
]

hr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('users/', include('apps.users.urls')),
    path('offers/', include('apps.offers.urls')),
    # path('usr/', include('apps.users.urls')),
    # path('addressing/', include('apps.addressing.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/companies/models.py
from django.db import models
from django.contrib.auth.models import User

from apps.offers.models import Offer


class Company(models.Model):
    """Model Company"""
    user_id = models.OneToOneField(User, on_delete=models.PROTECT)
    name = models.CharField(blank=True, max_length=100)
    offer_ids = models.ManyToManyField(Offer, blank=True)
    date_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return Name"""
        return self.name
    
    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Companies"

apps/home/models.py
from django.db import models

# Create your models here.

apps/offers/models.py
from django.db import models

from apps.users.models import Candidate


class Offer(models.Model):
    """Model Offer"""
    STATE_CONV = (
        ('OPEN', 'Abierta'),
        ('CLOSE', 'Cerrada'),
    )
    name = models.CharField(blank=True, max_length=100)
    date_close = models.DateTimeField()
    description = models.TextField()
    state = models.CharField(max_length=5, choices=STATE_CONV)
    date_create = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        """Return Name"""
        return self.name


class Process(models.Model):
    """Model Process"""
    STATE_ASP = (
        ('CANDIDATE', 'Aspirante'),
        ('SELECT', 'Seleccionado'),
        ('PROCESS', 'Proceso'),
        ('REJECTED', 'Rechazado'),
    )
    offer_id = models.ForeignKey(Offer, on_delete=models.CASCADE)
    candidate_id = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    state = models.CharField(max_length=12, choices=STATE_ASP)
    date_create = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        """Return state"""
        return self.state
    
    class Meta:
        ordering = ["date_create"]
        verbose_name_plural = "Process"

apps/users/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Candidate(models.Model):
    """Model Candidate"""
    TYPE_DOC = (
        ('CC', 'Cédula de ciudadanía'),
        ('CE', 'Cédula de extranjería'),
        ('PA', ' Pasaporte'),
    )
    user_id = models.OneToOneField(User, on_delete=models.PROTECT)
    type_document = models.CharField(max_length=2, choices=TYPE_DOC)
    identification = models.CharField(max_length=15)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    file_cv = models.ImageField(upload_to='files/cvs')
    date_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return first_name"""
        return self.first_name

    # def get_absolute_url(self):
    #     view_name = "detail_candidate"
    #     return reverse(view_name, kwargs={"id": self.id})

apps/companies/views.py
from django.shortcuts import render

# Create your views here.

apps/home/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView


class index(TemplateView):
    template_name = 'home/index.html'

apps/offers/views.py
from django.shortcuts import render

# Create your views here.

apps/users/views.py
from django.utils import timezone
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from apps.users.mixins import DashboardLoginRequiredMixin
from apps.users.models import Candidate
from django.views import View
from django.views.generic.edit import FormView
import requests
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from apps.users.models import Candidate


def loginView(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        instance = User.objects.filter(email=email)
        if len(instance) == 1:
            username = instance[0].username        
            user = authenticate(request, username=username, password=password)
            if user and instance[0].is_staff:
                login(request, user)
                return redirect('dashboard_admin')
            else:
                return render(request, 'users/login.html', {'error':'Usuario o Password incorrecto!'})
        return render(request, 'users/login.html', {'error':'El usuario {} no existe!'.format(email)})
    return render(request, 'users/login.html')

def logoutView(request):
    logout(request)
    return redirect('login')


class DashboardAdminView(DashboardLoginRequiredMixin, TemplateView):
    template_name = 'users/dashboard_admin.html'


class CandidateListView(DashboardLoginRequiredMixin, ListView):
    model = Candidate
    template_name = 'candidate_list.html'

    def get_queryset(self):
        queryset = Candidate.objects.all()
        return queryset


class CandidateDetailView(DashboardLoginRequiredMixin, DetailView):
    model = Candidate
    template_name = 'candidate_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CandidateDetailView, self).get_context_data(**kwargs)
        return context


class CandidateCreateView(View):
    template_name = 'users/candidate_form.html'

    def post(self, request, *args, **kwargs):
        pass

# def candidateCreateView(request):
#     if request.method == 'POST':
#         type_document = request.POST['type_document']
#         identification = request.POST['identification']
#         first_name = request.POST['first_name']
#         last_name = request.POST['last_name']
#         user_name = first_name[:1] + last_name.split()[0]
#         print('user_name', user_name)
#         # user_object = User(username=username, password=password)
#         # p.save()
#     return render(request, 'users/login.html')

apps/templates/base_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- iconos Font Awesome -->
    <script src="https://kit.fontawesome.com/c918795ee8.js" crossorigin="anonymous"></script>
    
    {% block link %}

    {% endblock %}

    {% block title %}

    {% endblock %}
</head>
<body>
    {% include 'nav_dashboard.html' %}
    {% block content %}
    
    {% endblock %}
 <!--  Scripts-->
 <!--  Scripts-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% block scripts %}
    
{% endblock %}
</body>
</html>

apps/templates/home/dashboard.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block title %}
    <title>HR | Dashboard</title>
{% endblock %}

{% block link %}
    <!-- <link rel="stylesheet" href="{% static 'css/offcanvas.css' %}"> -->
{% endblock %}

<!-- {% include 'navbar.html' %} -->
{% block content %}

  <div class="container">
    <h1>Estas autenticado</h1>
    <h2>{{user.id}}</h2>
    <h2>{{user.email}}</h2>
    <h2>{{user.username}}</h2>    
  </div>
{% endblock %}

apps/templates/home/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Hr | Home</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/pricing/">

    <!-- Bootstrap core CSS -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        html {
        font-size: 14px;
        }
        @media (min-width: 768px) {
        html {
            font-size: 16px;
        }
        }

        .container {
        max-width: 960px;
        }

        .pricing-header {
        max-width: 700px;
        }

        .card-deck .card {
        min-width: 220px;
        }
        
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="pricing.css" rel="stylesheet">
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">HR</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="#">Convocatorias</a>
  </nav>
  {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'dashboard_admin' %}">Ingreso</a>
  {% else %}
    <a class="btn btn-outline-primary" href="{% url 'login' %}">Ingreso</a>
  {% endif %}
  </div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Seleccion y Reclutamiento</h1>
  <p class="lead">Encuentra aqui las mejores convocatorias de trabajo, puedes aplicar de forma muy sencilla registrate <a href="{% url 'create_candidate' %}">aqui</a>.</p>
</div>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">&copy; 2020</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
      </div>
    </div>
  </footer>
</div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

apps/templates/nav_dashboard.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #337dff">
    <div class="container">
        <a class="navbar-brand" href="#">HR</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample07">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'dashboard_admin' %}">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'list_candidates' %}">Aspirantes<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <form class="form-inline my-2 my-md-0">
            <a href="{% url 'logout' %}" type="button" class="btn btn-danger">Salir</a>
        </form>
        </div>
    </div>
</nav>

apps/templates/users/candidate_detail.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block title %}
    <title>HR | {{ object.first_name }}</title>
{% endblock %}

{% block link %}
    
{% endblock %}


{% block content %}
<br>
<br>
<br>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dashboard_admin' %}">Inicio</a></li>
      <li class="breadcrumb-item"><a href="{% url 'candidate_list' %}">Library</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ object.first_name }}</li>
    </ol>
</nav>

{% endblock %}

apps/templates/users/candidate_form.html
{% extends "base_dashboard.html" %}
{% block title%}<title>Aspirante|Crear</title>{% endblock %}
{% block content %}
<h1>crear usuario</h1>
<div class="container">
    <br>
    <h3>Registro Aspirante</h3>
    <hr>
    {% if error %}
        {{ error }}
    {% endif %}
    <form method="POST" action="{% url 'create_candidate' %}">
        {% csrf_token %}
        <div class="form-group">
            <select class="form-control">
                <option value="CC">Cédula de ciudadanía</option>
                <option value="CE">Cédula de extranjería</option>
                <option value="PA"> Pasaporte</option>
            </select>
        </div>
        <div class="form-group">
            <label for="id_identification">Identification</label>
            <input type="text" name="identification" class="form-control" id="id_identification" required>
        </div>
        <div class="form-group">
            <label for="id_first_name">Nombres</label>
            <input type="text" name="first_name" maxlength="50" class="form-control" id="id_first_name" required>
        </div>
        <div class="form-group">
            <label for="id_last_name">Apellidos</label>
            <input type="text" name="last_name" maxlength="50" class="form-control" id="id_last_name" required>
        </div>
        <div class="form-group">
            <label for="id_file_cv">Adjunta tu HV</label>
            <input type="file" name="file_cv" accept="image/*" class="form-control-file" id="id_file_cv">
          </div>
        <button type="submit" class="btn btn-primary">Registrarse</button>
    </form>
</div>
{% endblock %}

apps/templates/users/candidate_list.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block title %}
    <title>HR | Lista Aspirantes</title>
{% endblock %}

{% block link %}
    
{% endblock %}


{% block content %}
<br>
<br>
<br>

<div class="container">
    {% if object_list %}
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Nombres</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Tipo Documento</th>
            <th scope="col">Identificacion</th>
            <th scope="col">Ver Detalle</th>
          </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{ object.first_name }}</td>
            <td>{{ object.last_name }}</td>
            <td>{{ object.type_document }}</td>
            <td>{{ object.identification }}</td>
            <td><a href="{% url 'detail_candidates' object.pk %}">Ver</a></td>
          </tr>
        {% endfor %}
        </tbody>
        </table>
        {% else %}
        <div>
            <div class="alert alert-primary" role="alert">
                A simple primary alert—check it out!
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}

apps/templates/users/dashboard_admin.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block title %}
    <title>HR | Dashboard Admin</title>
{% endblock %}

{% block link %}
    <!-- <link rel="stylesheet" href="{% static 'css/offcanvas.css' %}"> -->
{% endblock %}

<!-- {% include 'navbar.html' %} -->
{% block content %}

  <div class="container">
    
  </div>
{% endblock %}

apps/templates/users/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Hr | Ingreso </title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- iconos Font Awesome -->
    <script src="https://kit.fontawesome.com/c918795ee8.js" crossorigin="anonymous"></script>

    {% block link %}
      <link rel="stylesheet" href="{% static 'css/signin.css' %}">
    {% endblock %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
   
    <form class="form-signin" method="post" action="{% url 'login' %}"> {% csrf_token %}
      <span style="font-size: 68px; color: Dodgerblue;">
          <a href="{% url 'index' %}"><i class="fas fa-laptop-house"></i></a>
      </span>
      <h1 class="h3 mb-3 font-weight-normal">Acceder</h1>
      {% if error %}
        <p style="color: red;">{{ error }}</p>
      {% endif %}
      <label for="inputEmail" class="sr-only">Correo Electronico</label>
      <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Correo Electronico" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
            <a href="{% url 'index' %}">Si aun no tienes cuenta regitrate.</a>
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Ingresa</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
  </form>

<!--  Scripts-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

apps/templates/users/logout.html
<p>Sesion Cerrada!</p>
<a href="{% url 'login'%}">Click aqui si quieres volver a ingresar.</a>